# Generated by Django 4.2.14 on 2024-11-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0003_post_banner'),
    ]

    operations = [
        # hộp
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # tiêu chuẩn
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # tiêu chí
        migrations.CreateModel(
            name='criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.standard')),
            ],
        ),
        # minh chứng
        migrations.CreateModel(
            name='attest',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('performer', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(blank=True, default='fallback.jpeg', upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.box')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.criterion')),
            ],
        ),
    ]
