# Generated by Django 4.2.14 on 2024-12-14 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0004_box_standard_uploadedfile_alter_post_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attest',
            name='attest_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attest',
            name='attest_stt',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='media/'),
        ),
        migrations.AddConstraint(
            model_name='attest',
            constraint=models.UniqueConstraint(fields=('attest_id', 'attest_stt'), name='unique_attest_id_attest_stt'),
        ),
    ]
