# Generated by Django 4.2.14 on 2024-12-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0005_add_new_fields_to_attest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attest',
            options={'verbose_name': 'Minh chứng', 'verbose_name_plural': 'Các minh chứng'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Hộp', 'verbose_name_plural': 'Các hộp'},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name': 'Tiêu chí', 'verbose_name_plural': 'Các tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'Tiêu chuẩn', 'verbose_name_plural': 'Các tiêu chuẩn'},
        ),
        migrations.AlterField(
            model_name='attest',
            name='attest_stt',
            field=models.CharField(max_length=10, verbose_name='STT'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='body',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.box', verbose_name='Hộp'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.criterion', verbose_name='Tiêu chí'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='image',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='', verbose_name='Hình'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='performer',
            field=models.TextField(verbose_name='Nơi ban hành'),
        ),
        migrations.AlterField(
            model_name='attest',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Minh chứng'),
        ),
        migrations.AlterField(
            model_name='box',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='box',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='box',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Hộp'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.standard', verbose_name='Tiêu chuẩn'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tiêu chí'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='standard',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tiêu chuẩn'),
        ),
    ]
