# Generated by Django 4.2.14 on 2025-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0007_attest_is_common_alter_box_id_common_attest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
