# Generated by Django 4.2.14 on 2025-01-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0008_alter_criterion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_attest',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CTDT.criterion', verbose_name='Tiêu chí'),
        ),
    ]
