# Generated by Django 4.2.14 on 2025-01-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0009_common_attest_criterion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common_attest',
            name='id',
        ),
        migrations.AlterField(
            model_name='common_attest',
            name='common_attest_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='common_attest',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTDT.criterion', verbose_name='Tiêu chí'),
        ),
    ]
