# Generated by Django 4.2.14 on 2025-01-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0010_remove_common_attest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attest',
            name='common_attest',
        ),
    ]
