# Generated by Django 4.2.14 on 2025-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0013_attest_updated_on_box_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
