# Generated by Django 4.2.14 on 2025-02-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0014_alter_standard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='CTDT.attest')),
            ],
        ),
    ]
