# Generated by Django 4.2.14 on 2025-02-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0015_showphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowPhoto',
            new_name='PhotoAttest',
        ),
        migrations.AlterModelOptions(
            name='photoattest',
            options={'verbose_name': 'Hình ảnh', 'verbose_name_plural': 'Các hình ảnh'},
        ),
        migrations.RemoveField(
            model_name='attest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='common_attest',
            name='image',
        ),
        migrations.CreateModel(
            name='PhotoCommonAttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='CTDT.common_attest')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Các hình ảnh',
            },
        ),
    ]
