# Generated by Django 4.2.14 on 2025-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0018_profileuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoattest',
            options={'verbose_name': 'Hình ảnh', 'verbose_name_plural': 'Các hình ảnh'},
        ),
        migrations.RemoveConstraint(
            model_name='attest',
            name='unique_attest_id_attest_stt',
        ),
        migrations.AlterField(
            model_name='attest',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Là minh chứng DC'),
        ),
        migrations.AlterField(
            model_name='common_attest',
            name='common_attest_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID Minh chứng DC'),
        ),
        migrations.AddConstraint(
            model_name='attest',
            constraint=models.UniqueConstraint(fields=('attest_id', 'attest_stt', 'criterion'), name='unique_attest_id_attest_stt_criterion'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_standard_title'),
        ),
    ]
