# Generated by Django 4.2.14 on 2025-04-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0019_alter_photoattest_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attest',
            name='unique_attest_id_attest_stt_criterion',
        ),
    ]
