# Generated by Django 4.2.14 on 2025-06-29 00:20

import CTDT.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0020_remove_attest_unique_attest_id_attest_stt_criterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFScanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=CTDT.models.pdf_upload_to, verbose_name='File PDF scan')),
                ('attest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='CTDT.attest', verbose_name='Minh chứng')),
            ],
            options={
                'verbose_name': 'Tệp PDF scan',
                'verbose_name_plural': 'Các tệp PDF scan',
            },
        ),
    ]
