# Generated by Django 4.2.14 on 2026-06-20 00:10

import CTDT.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0021_pdfscanfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên ngành')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('slug', models.SlugField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ngành',
                'verbose_name_plural': 'Các ngành',
            },
        ),
        # migrations.AlterField(
        #     model_name='pdfscanfile',
        #     name='file',
        #     field=models.FileField(blank=True, upload_to=CTDT.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='File PDF scan'),
        # ),
        migrations.AddField(
            model_name='box',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='CTDT.major', verbose_name='Ngành'),
        ),
    ]
