# Generated by Django 4.2.14 on 2026-06-20 15:01

import CTDT.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTDT', '0022_major_alter_pdfscanfile_file_box_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfscanfile',
            name='file',
            field=models.FileField(blank=True, upload_to=CTDT.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='File PDF scan'),
        ),
        migrations.CreateModel(
            name='PDFCommonAttestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=CTDT.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='File PDF scan')),
                ('common_attest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='CTDT.common_attest', verbose_name='Minh chứng dùng chung')),
            ],
            options={
                'verbose_name': 'Tệp PDF dùng chung',
                'verbose_name_plural': 'Các tệp PDF dùng chung',
            },
        ),
    ]
